# Generated by Django 4.2.4 on 2023-08-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amigos',
            new_name='Amigo',
        ),
    ]
